# -----------------------------------------------------------------------------
# Build Asciidoctor PDF sample syntax file with theme
# Author: Urs Roesch https://github.com/uroesch
# Version: 0.2.0
# -----------------------------------------------------------------------------
name: build-css-theme

on:
  push:
    branches:
    - workflow/*
  pull_request:
    branches:
    - master
    - main

jobs:
  build-css-theme:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    container: 
      image: uroesch/asciidoctor:latest
    strategy:
      fail-fast: true

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build theme
      shell: bash
      run: rake 

    - name: Create test document
      shell: bash
      run: rake test 
